CREATE TABLE CONSULTAS_CLIENTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    data_consulta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_client BIGINT NOT NULL,
    id_consulta BIGINT NOT NULL,
    CONSTRAINT FK_CONSULTA FOREIGN KEY (id_consulta) REFERENCES CONSULTAS(id) ON DELETE CASCADE,
    CONSTRAINT FK_CLIENT FOREIGN KEY (id_client) REFERENCES CLIENTS(id) ON DELETE CASCADE
);
